# Generated by Django 4.2.4 on 2023-10-11 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_usuario_perfil_alter_perfil_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="password",
        ),
    ]
