# Generated by Django 4.2.4 on 2023-10-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0002_alter_osc_options_alter_osc_articulosinteres_and_more"),
        ("users", "0004_remove_perfil_apellido_remove_perfil_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="favoritos",
            field=models.ManyToManyField(blank=True, to="orgs.osc"),
        ),
    ]
